export const TideABI = [
  'constructor(uint256,uint256)',
  'event Approval(address indexed,address indexed,uint256)',
  'event OwnershipTransferred(address indexed,address indexed)',
  'event Transfer(address indexed,address indexed,uint256)',
  'function allowance(address,address) view returns (uint256)',
  'function approve(address,uint256) returns (bool)',
  'function balanceOf(address) view returns (uint256)',
  'function blockReward() view returns (uint256)',
  'function burn(uint256)',
  'function burnFrom(address,uint256)',
  'function cap() view returns (uint256)',
  'function decimals() view returns (uint8)',
  'function decreaseAllowance(address,uint256) returns (bool)',
  'function increaseAllowance(address,uint256) returns (bool)',
  'function name() view returns (string)',
  'function owner() view returns (address)',
  'function renounceOwnership()',
  'function setBlockReward(uint256)',
  'function symbol() view returns (string)',
  'function totalSupply() view returns (uint256)',
  'function transfer(address,uint256) returns (bool)',
  'function transferFrom(address,address,uint256) returns (bool)',
  'function transferOwnership(address)',
];
